## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [4]:
attrition_df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [9]:
# Create a list of at least 10 column names to use as X data
X_column_list = ['Age', 'BusinessTravel', 'DistanceFromHome',
                 'EnvironmentSatisfaction', 'HourlyRate',
                 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
                 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
                 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
                 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
                 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
                 'YearsWithCurrManager']


# Create X_df using your selected columns
X_df = attrition_df[X_column_list]

# Show the data types for X_df
X_df.dtypes


Age                          int64
BusinessTravel              object
DistanceFromHome             int64
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [10]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df)



In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# See following cells for encoding processes


No     788
Yes    314
Name: OverTime, dtype: int64

In [11]:
# Look at the 3 columns with object data types to understand best way to encode.
X_df[['BusinessTravel', 'JobRole', 'OverTime']]

BusinessTravel                    JobRole OverTime
0         Travel_Rarely            Sales Executive      Yes
1     Travel_Frequently         Research Scientist       No
2         Travel_Rarely      Laboratory Technician      Yes
3     Travel_Frequently         Research Scientist      Yes
4         Travel_Rarely      Laboratory Technician       No
...                 ...                        ...      ...
1465  Travel_Frequently      Laboratory Technician       No
1466      Travel_Rarely  Healthcare Representative       No
1467      Travel_Rarely     Manufacturing Director      Yes
1468  Travel_Frequently            Sales Executive       No
1469      Travel_Rarely      Laboratory Technician       No

[1470 rows x 3 columns]

In [14]:
# Check for null values
null_counts = X_df.isnull().sum()
print(null_counts)

Age                         0
BusinessTravel              0
DistanceFromHome            0
EnvironmentSatisfaction     0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64


In [18]:
# Create lists for OneHotEncoder and LabelEncoder

enc_columns = ['BusinessTravel', 'OverTime']
LE_columns = ['JobRole']

In [34]:
# Create a OneHotEncoder for BusinessTravel and Overtime columns
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='if_binary', sparse=False)

# encode the columns included in the enc_columns list. Do this for both train and test sets.
X_encoded_array_train = encoder.fit_transform(X_train[enc_columns])
X_encoded_array_test = encoder.fit_transform(X_test[enc_columns])

print(X_encoded_array_train[0:5])
print(X_encoded_array_test[0:5])

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 1. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [1. 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [37]:
# use get feature names to get list of columns
encoded_columns = encoder.get_feature_names_out(enc_columns)

# convert encoded arrays into dataframes
X_enc_train = pd.DataFrame(X_encoded_array_train, columns=encoded_columns)
X_enc_test = pd.DataFrame(X_encoded_array_test, columns=encoded_columns)

X_enc_test


BusinessTravel_Non-Travel  BusinessTravel_Travel_Frequently  \
0                          0.0                               0.0   
1                          0.0                               0.0   
2                          0.0                               1.0   
3                          0.0                               0.0   
4                          1.0                               0.0   
..                         ...                               ...   
363                        0.0                               0.0   
364                        0.0                               1.0   
365                        0.0                               0.0   
366                        0.0                               0.0   
367                        0.0                               1.0   

     BusinessTravel_Travel_Rarely  OverTime_Yes  
0                             1.0           0.0  
1                             1.0           1.0  
2                             0.0           0.0  
3                             1.0           1.0  
4                             0.0           0.0  
..                            ...           ...  
363                           1.0           0.0  
364                           0.0           1.0  
365                           1.0           0.0  
366                           1.0           0.0  
367                           0.0           0.0  

[368 rows x 4 columns]

In [43]:
# Create Label Encoder for JobRole column. Using Label encoder because there are 9 different possible responses and want to avoid adding 9 additional columns.

from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

# Create copy of X_df to use Label Encoder. Will then concatenate that LE dataframe with the OneHotEncoder df. Will need to remember to drop the original un-encoded columns

X_train_label_encoded = X_train.copy()
X_test_label_encoded = X_test.copy()

for column in LE_columns:
  X_train_label_encoded[column] = LE.fit_transform(X_train_label_encoded[column])
  X_test_label_encoded[column] = LE.fit_transform(X_test_label_encoded[column])

X_train_label_encoded.reset_index(drop=True, inplace=True)
X_test_label_encoded.reset_index(drop=True, inplace=True)

X_test_label_encoded




Age     BusinessTravel  DistanceFromHome  EnvironmentSatisfaction  \
0     36      Travel_Rarely                16                        3   
1     53      Travel_Rarely                 6                        2   
2     51  Travel_Frequently                 2                        2   
3     35      Travel_Rarely                16                        4   
4     45         Non-Travel                 6                        4   
..   ...                ...               ...                      ...   
363   50      Travel_Rarely                 2                        3   
364   33  Travel_Frequently                 1                        1   
365   38      Travel_Rarely                 1                        2   
366   26      Travel_Rarely                 2                        4   
367   31  Travel_Frequently                24                        4   

     HourlyRate  JobInvolvement  JobLevel  JobRole  JobSatisfaction  \
0            43               4         1        2                1   
1            34               3         2        8                3   
2            52               3         3        7                2   
3            72               3         3        0                3   
4            57               2         3        7                4   
..          ...             ...       ...      ...              ...   
363          64               3         4        5                3   
364          98               3         3        5                4   
365          33               4         2        0                4   
366          32               4         2        4                4   
367          30               3         2        4                4   

     NumCompaniesWorked  ... PerformanceRating  RelationshipSatisfaction  \
0                     1  ...                 3                         3   
1                     2  ...                 4                         4   
2                     2  ...                 3                         2   
3                     4  ...                 3                         3   
4                     6  ...                 3                         4   
..                  ...  ...               ...                       ...   
363                   5  ...                 3                         4   
364                   1  ...                 3                         3   
365                   0  ...                 3                         3   
366                   1  ...                 3                         2   
367                   2  ...                 4                         4   

     StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                   0                 18                      1   
1                   1                 13                      3   
2                   0                 14                      5   
3                   0                 10                      2   
4                   0                 23                      2   
..                ...                ...                    ...   
363                 0                 30                      3   
364                 0                 15                      1   
365                 0                 10                      4   
366                 0                  8                      2   
367                 0                  9                      3   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  3              17                  13   
1                  1               7                   7   
2                  3               4                   2   
3                  3               8                   7   
4                  3              19                   7   
..               ...             ...                 ...   
363                3               4                   3   
364                3              15                  14   
365  

In [46]:
# Merge OneHotEncoded dataframe to label encoded dataframe and drop original unencoded columns
# Used merge because putting together dataframes with different column names.

X_train_final = pd.merge(X_train_label_encoded, X_enc_train, left_index=True, right_index=True, how='inner')
X_test_final = pd.merge(X_test_label_encoded, X_enc_test, left_index=True, right_index=True, how='inner')


X_train_final.reset_index(drop=True, inplace=True)
X_test_final.reset_index(drop=True, inplace=True)

X_train_final.drop(['BusinessTravel', 'OverTime'], axis=1, inplace=True)
X_test_final.drop(['BusinessTravel', 'OverTime'], axis=1, inplace=True)

X_test_final

Age  DistanceFromHome  EnvironmentSatisfaction  HourlyRate  \
0     36                16                        3          43   
1     53                 6                        2          34   
2     51                 2                        2          52   
3     35                16                        4          72   
4     45                 6                        4          57   
..   ...               ...                      ...         ...   
363   50                 2                        3          64   
364   33                 1                        1          98   
365   38                 1                        2          33   
366   26                 2                        4          32   
367   31                24                        4          30   

     JobInvolvement  JobLevel  JobRole  JobSatisfaction  NumCompaniesWorked  \
0                 4         1        2                1                   1   
1                 3         2        8                3                   2   
2                 3         3        7                2                   2   
3                 3         3        0                3                   4   
4                 2         3        7                4                   6   
..              ...       ...      ...              ...                 ...   
363               3         4        5                3                   5   
364               3         3        5                4                   1   
365               4         2        0                4                   0   
366               4         2        4                4                   1   
367               3         2        4                4                   2   

     PercentSalaryHike  ...  TrainingTimesLastYear  WorkLifeBalance  \
0                   16  ...                      1                3   
1                   20  ...                      3                1   
2                   11  ...                      5                3   
3                   12  ...                      2                3   
4                   12  ...                      2                3   
..                 ...  ...                    ...              ...   
363                 16  ...                      3                3   
364                 12  ...                      1                3   
365                 13  ...                      4                2   
366                 12  ...                      2                3   
367                 20  ...                      3                2   

     YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                17                  13                       15   
1                 7                   7                        4   
2                 4                   2                        3   
3                 8                   7                        0   
4                19                   7                       12   
..              ...                 ...                      ...   
363               4                   3                        0   
364              15                  14                        8   
365               9                   7                        1   
366               8                   7                        1   
367               5                   4                        1   

     YearsWithCurrManager  BusinessTravel_Non-Travel  \
0                      14                        0.0   
1                       5                        0.0   
2                       2                        0.0   
3                       0                        0.0   
4                       8                        1.0   
..                    ...                        ...   
363                     3                        0.0   
364                    12                        0.0   
365                     8                        0.0   
366                  

In [47]:
X_train_final.columns

Index(['Age', 'DistanceFromHome', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'BusinessTravel_Non-Travel', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'OverTime_Yes'],
      dtype='object')

In [49]:
# Create a StandardScaler
X_scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler.fit(X_train_final)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train_final)
X_test_scaled = X_scaler.transform(X_test_final)


In [ ]:
# Create a OneHotEncoder for the Department column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data




array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
# Create a OneHotEncoder for the Attrition column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data



array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Create, Compile, and Train the Model

In [ ]:
# Find the number of columns in the X training data


# Create the input layer


# Create at least two shared layers


In [ ]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer



In [ ]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer



In [ ]:
# Create the model


# Compile the model


# Summarize the model


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input (InputLayer)          [(None, 10)]                 0         []                            
                                                                                                  
 shared1 (Dense)             (None, 64)                   704       ['input[0][0]']               
                                                                                                  
 shared2 (Dense)             (None, 128)                  8320      ['shared1[0][0]']             
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared2[0][0]']             
                                                                                              

In [ ]:
# Train the model



Epoch 1/100
35/35 [==============================] - 14s 25ms/step - loss: 1.4162 - department_output_loss: 0.8374 - attrition_output_loss: 0.5787 - department_output_accuracy: 0.6316 - attrition_output_accuracy: 0.7024
Epoch 2/100
35/35 [==============================] - 1s 27ms/step - loss: 1.2070 - department_output_loss: 0.7661 - attrition_output_loss: 0.4408 - department_output_accuracy: 0.6570 - attrition_output_accuracy: 0.8403
Epoch 3/100
35/35 [==============================] - 0s 13ms/step - loss: 1.1520 - department_output_loss: 0.7539 - attrition_output_loss: 0.3981 - department_output_accuracy: 0.6570 - attrition_output_accuracy: 0.8403
Epoch 4/100
35/35 [==============================] - 0s 14ms/step - loss: 1.1231 - department_output_loss: 0.7452 - attrition_output_loss: 0.3779 - department_output_accuracy: 0.6588 - attrition_output_accuracy: 0.8475
Epoch 5/100
35/35 [==============================] - 0s 12ms/step - loss: 1.1031 - department_output_loss: 0.7342 - attriti

In [ ]:
# Evaluate the model with the testing data


12/12 [==============================] - 0s 3ms/step - loss: 4.1624 - department_output_loss: 3.1143 - attrition_output_loss: 1.0481 - department_output_accuracy: 0.5272 - attrition_output_accuracy: 0.8261


[4.162380218505859,
 3.114327907562256,
 1.0480519533157349,
 0.5271739363670349,
 0.8260869383811951]

In [ ]:
# Print the accuracy for both department and attrition


Department predictions accuracy: 0.5271739363670349
Attrition predictions accuracy: 0.8260869383811951


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.