## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Dense, concatenate

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
attrition_df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [5]:
# Create a list of at least 10 column names to use as X data
X_column_list = ['Age', 'BusinessTravel', 'DistanceFromHome',
                 'EnvironmentSatisfaction', 'HourlyRate',
                 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
                 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
                 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
                 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
                 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
                 'YearsWithCurrManager']


# Create X_df using your selected columns
X_df = attrition_df[X_column_list]

# Show the data types for X_df
X_df.dtypes


Age                          int64
BusinessTravel              object
DistanceFromHome             int64
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df)



In [7]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# See following cells for encoding processes


In [8]:
# Look at the 3 columns with object data types to understand best way to encode.
X_df[['BusinessTravel', 'JobRole', 'OverTime']]

BusinessTravel                    JobRole OverTime
0         Travel_Rarely            Sales Executive      Yes
1     Travel_Frequently         Research Scientist       No
2         Travel_Rarely      Laboratory Technician      Yes
3     Travel_Frequently         Research Scientist      Yes
4         Travel_Rarely      Laboratory Technician       No
...                 ...                        ...      ...
1465  Travel_Frequently      Laboratory Technician       No
1466      Travel_Rarely  Healthcare Representative       No
1467      Travel_Rarely     Manufacturing Director      Yes
1468  Travel_Frequently            Sales Executive       No
1469      Travel_Rarely      Laboratory Technician       No

[1470 rows x 3 columns]

In [9]:
# Check for null values
null_counts = X_df.isnull().sum()
print(null_counts)

Age                         0
BusinessTravel              0
DistanceFromHome            0
EnvironmentSatisfaction     0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64


In [10]:
# Create lists for OneHotEncoder and LabelEncoder

enc_columns = ['BusinessTravel', 'OverTime']
LE_columns = ['JobRole']

In [11]:
# Create a OneHotEncoder for BusinessTravel and Overtime columns
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='if_binary', sparse=False)

# encode the columns included in the enc_columns list. Do this for both train and test sets.
X_encoded_array_train = encoder.fit_transform(X_train[enc_columns])
X_encoded_array_test = encoder.fit_transform(X_test[enc_columns])

print(X_encoded_array_train[0:5])
print(X_encoded_array_test[0:5])

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [12]:
# use get feature names to get list of columns
encoded_columns = encoder.get_feature_names_out(enc_columns)

# convert encoded arrays into dataframes
X_enc_train = pd.DataFrame(X_encoded_array_train, columns=encoded_columns)
X_enc_test = pd.DataFrame(X_encoded_array_test, columns=encoded_columns)

X_enc_test


BusinessTravel_Non-Travel  BusinessTravel_Travel_Frequently  \
0                          0.0                               1.0   
1                          0.0                               1.0   
2                          0.0                               0.0   
3                          0.0                               0.0   
4                          0.0                               1.0   
..                         ...                               ...   
363                        0.0                               0.0   
364                        0.0                               0.0   
365                        0.0                               0.0   
366                        0.0                               1.0   
367                        0.0                               0.0   

     BusinessTravel_Travel_Rarely  OverTime_Yes  
0                             0.0           0.0  
1                             0.0           0.0  
2                             1.0           1.0  
3                             1.0           0.0  
4                             0.0           0.0  
..                            ...           ...  
363                           1.0           0.0  
364                           1.0           0.0  
365                           1.0           0.0  
366                           0.0           0.0  
367                           1.0           0.0  

[368 rows x 4 columns]

In [13]:
# Create Label Encoder for JobRole column. Using Label encoder because there are 9 different possible responses and want to avoid adding 9 additional columns.

from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

# Create copy of X_df to use Label Encoder. Will then concatenate that LE dataframe with the OneHotEncoder df. Will need to remember to drop the original un-encoded columns

X_train_label_encoded = X_train.copy()
X_test_label_encoded = X_test.copy()

for column in LE_columns:
  X_train_label_encoded[column] = LE.fit_transform(X_train_label_encoded[column])
  X_test_label_encoded[column] = LE.fit_transform(X_test_label_encoded[column])

X_train_label_encoded.reset_index(drop=True, inplace=True)
X_test_label_encoded.reset_index(drop=True, inplace=True)

X_test_label_encoded




Age     BusinessTravel  DistanceFromHome  EnvironmentSatisfaction  \
0     27  Travel_Frequently                 2                        4   
1     28  Travel_Frequently                 1                        1   
2     26      Travel_Rarely                 1                        2   
3     28      Travel_Rarely                17                        3   
4     36  Travel_Frequently                11                        2   
..   ...                ...               ...                      ...   
363   36      Travel_Rarely                 2                        4   
364   33      Travel_Rarely                10                        1   
365   40      Travel_Rarely                 2                        3   
366   51  Travel_Frequently                 2                        2   
367   20      Travel_Rarely                 1                        4   

     HourlyRate  JobInvolvement  JobLevel  JobRole  JobSatisfaction  \
0            43               1         2        7                4   
1            45               2         1        2                2   
2            90               2         1        6                3   
3            32               2         1        2                4   
4            95               2         2        4                2   
..          ...             ...       ...      ...              ...   
363          96               3         1        6                3   
364          38               1         1        2                4   
365          79               3         5        3                3   
366          52               3         3        7                2   
367          83               2         1        6                2   

     NumCompaniesWorked  ... PerformanceRating  RelationshipSatisfaction  \
0                     3  ...                 4                         2   
1                     1  ...                 3                         1   
2                     1  ...                 3                         3   
3                     5  ...                 3                         1   
4                     1  ...                 3                         3   
..                  ...  ...               ...                       ...   
363                   4  ...                 3                         2   
364                   7  ...                 3                         1   
365                   0  ...                 3                         4   
366                   2  ...                 3                         2   
367                   1  ...                 3                         4   

     StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                   0                  8                      3   
1                   2                  1                      2   
2                   1                  1                      3   
3                   1                  6                      2   
4                   0                  6                      3   
..                ...                ...                    ...   
363                 1                  6                      3   
364                 3                  8                      2   
365                 0                 21                      2   
366                 0                 14                      5   
367                 0                  1                      0   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  3               6                   2   
1                  3               1                   0   
2                  2               1                   0   
3                  2               4                   1   
4                  3               6                   5   
..               ...             ...                 ...   
363                3               2                   2   
364                3               4                   3   
365  

In [14]:
# Merge OneHotEncoded dataframe to label encoded dataframe and drop original unencoded columns
# Used merge because putting together dataframes with different column names.

X_train_final = pd.merge(X_train_label_encoded, X_enc_train, left_index=True, right_index=True, how='inner')
X_test_final = pd.merge(X_test_label_encoded, X_enc_test, left_index=True, right_index=True, how='inner')


X_train_final.reset_index(drop=True, inplace=True)
X_test_final.reset_index(drop=True, inplace=True)

X_train_final.drop(['BusinessTravel', 'OverTime'], axis=1, inplace=True)
X_test_final.drop(['BusinessTravel', 'OverTime'], axis=1, inplace=True)

X_test_final

Age  DistanceFromHome  EnvironmentSatisfaction  HourlyRate  \
0     27                 2                        4          43   
1     28                 1                        1          45   
2     26                 1                        2          90   
3     28                17                        3          32   
4     36                11                        2          95   
..   ...               ...                      ...         ...   
363   36                 2                        4          96   
364   33                10                        1          38   
365   40                 2                        3          79   
366   51                 2                        2          52   
367   20                 1                        4          83   

     JobInvolvement  JobLevel  JobRole  JobSatisfaction  NumCompaniesWorked  \
0                 1         2        7                4                   3   
1                 2         1        2                2                   1   
2                 2         1        6                3                   1   
3                 2         1        2                4                   5   
4                 2         2        4                2                   1   
..              ...       ...      ...              ...                 ...   
363               3         1        6                3                   4   
364               1         1        2                4                   7   
365               3         5        3                3                   0   
366               3         3        7                2                   2   
367               2         1        6                2                   1   

     PercentSalaryHike  ...  TrainingTimesLastYear  WorkLifeBalance  \
0                   20  ...                      3                3   
1                   15  ...                      2                3   
2                   13  ...                      3                2   
3                   12  ...                      2                2   
4                   13  ...                      3                3   
..                 ...  ...                    ...              ...   
363                 13  ...                      3                3   
364                 13  ...                      2                3   
365                 14  ...                      2                3   
366                 11  ...                      5                3   
367                 13  ...                      0                4   

     YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                 6                   2                        0   
1                 1                   0                        0   
2                 1                   0                        1   
3                 4                   1                        0   
4                 6                   5                        0   
..              ...                 ...                      ...   
363               2                   2                        2   
364               4                   3                        1   
365              20                  15                        1   
366               4                   2                        3   
367               1                   0                        0   

     YearsWithCurrManager  BusinessTravel_Non-Travel  \
0                       0                        0.0   
1                       0                        0.0   
2                       0                        0.0   
3                       3                        0.0   
4                       3                        0.0   
..                    ...                        ...   
363                     2                        0.0   
364                     3                        0.0   
365                    12                        0.0   
366                  

In [15]:
X_train_final.columns

Index(['Age', 'DistanceFromHome', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'BusinessTravel_Non-Travel', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'OverTime_Yes'],
      dtype='object')

In [16]:
# Create a StandardScaler
X_scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler.fit(X_train_final)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train_final)
X_test_scaled = X_scaler.transform(X_test_final)


In [17]:
# Create a OneHotEncoder for the Department column
y_encoder_dept = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data

y_encoded_dept_train = y_encoder_dept.fit_transform(y_train[['Department']])
y_encoded_dept_test = y_encoder_dept.fit_transform(y_test[['Department']])

print(y_encoded_dept_train[0:5])
print(y_encoded_dept_test[0:5])


[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [18]:
# Create a OneHotEncoder for the Attrition column
y_encoder_attr = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data

y_encoded_attr_train = y_encoder_dept.fit_transform(y_train[['Attrition']])
y_encoded_attr_test = y_encoder_dept.fit_transform(y_test[['Attrition']])

print(y_encoded_attr_train[0:5])
print(y_encoded_attr_test[0:5])


[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## Create, Compile, and Train the Model

In [19]:
# Find the number of columns in the X training data
input_nodes = len(X_train_final.columns)

# Create the input layer
input_layer = layers.Input(shape=(input_nodes,), name='input_layer')

# Create at least two shared layers. Started with 24 neurons, because that is the number of inputs
shared_layer1 = layers.Dense(24, activation='relu', name='shared_layer1')(input_layer)
shared_layer2 = layers.Dense(12, activation= 'relu', name='shared_layer2')(shared_layer1)


In [25]:
# Create a branch for Department
# with a hidden layer and an output layer


# Create the hidden layer
dept_hidden = Dense(6, activation='relu', name='dept_hidden')(shared_layer2)

# Create the output layer. Using softmax because there are 3 possible departments and want to know the probability in relation to each other.
dept_output = Dense(3, activation='softmax', name='dept_output')(dept_hidden)


In [29]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_hidden = Dense(6, activation='relu', name='attr_hidden')(shared_layer2)

# Create the output layer
attr_output = Dense(2, activation='sigmoid', name='attr_output')(attr_hidden)


In [32]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, attr_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy',
                    'attr_output': 'binary_crossentropy'},
              metrics={'dept_output': 'accuracy',
                       'attr_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_layer (InputLayer)    [(None, 24)]                 0         []                            
                                                                                                  
 shared_layer1 (Dense)       (None, 24)                   600       ['input_layer[0][0]']         
                                                                                                  
 shared_layer2 (Dense)       (None, 12)                   300       ['shared_layer1[0][0]']       
                                                                                                  
 dept_hidden (Dense)         (None, 6)                    78        ['shared_layer2[0][0]']       
                                                                                            

In [33]:
# Train the model
model.fit(
    X_train_final,
    {'dept_output': y_encoded_dept_train, 'attr_output': y_encoded_attr_train},
    epochs = 10,
    batch_size = 32
)



Epoch 1/10
35/35 [==============================] - 2s 4ms/step - loss: 3.1632 - dept_output_loss: 2.1588 - attr_output_loss: 1.0044 - dept_output_accuracy: 0.6497 - attr_output_accuracy: 0.3457
Epoch 2/10
35/35 [==============================] - 0s 3ms/step - loss: 1.7635 - dept_output_loss: 1.0661 - attr_output_loss: 0.6974 - dept_output_accuracy: 0.6506 - attr_output_accuracy: 0.7314
Epoch 3/10
35/35 [==============================] - 0s 3ms/step - loss: 1.6594 - dept_output_loss: 0.9890 - attr_output_loss: 0.6704 - dept_output_accuracy: 0.6425 - attr_output_accuracy: 0.8285
Epoch 4/10
35/35 [==============================] - 0s 4ms/step - loss: 1.5949 - dept_output_loss: 0.9351 - attr_output_loss: 0.6598 - dept_output_accuracy: 0.6479 - attr_output_accuracy: 0.8330
Epoch 5/10
35/35 [==============================] - 0s 4ms/step - loss: 1.5343 - dept_output_loss: 0.8842 - attr_output_loss: 0.6501 - dept_output_accuracy: 0.6497 - attr_output_accuracy: 0.8376
Epoch 6/10
35/35 [=======

In [34]:
# Evaluate the model with the testing data
results = model.evaluate(np.array(X_test_final), {
    'dept_output': y_encoded_dept_test,
    'attr_output': y_encoded_attr_test
})

12/12 [==============================] - 1s 4ms/step - loss: 1.3393 - dept_output_loss: 0.7376 - attr_output_loss: 0.6017 - dept_output_accuracy: 0.6766 - attr_output_accuracy: 0.8424


In [36]:
# Print the accuracy for both department and attrition
pred_categories = ['Attrition', 'Department']
for i, cat in enumerate(pred_categories):
    print(f"{cat} accuracy: {results[i+1]}")

Attrition accuracy: 0.7375898957252502
Department accuracy: 0.6017428636550903


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.